sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qgdL9YQJj9b0SLfrtJJjyJpckdBHeqxXbDviYU2iiHytpwW2DJsvSkbehrgDj8lsOEG99lWC17N7VQbByHe+QN3pxM8h8X96gabt2UcbirfFhl65ocLRPipyEue1sHeXdx5Bi5pehIro/29zJMk06dvc91gXu9/tfbZaWyR3vSaV5F+8y9LF5/bu2gI4iTC2ZCxYLJisa7hqf+UAMnJtuXILLgE6WU2iFoGH9sGWST3glt4w7b8froYt5gkuMNNz2jNyNu1B6IwiC47KnHSPjh4gC8Cbm6tR1t+wc31zTEusQVvOwOg4siU+fdBnHg5rPpE0XgooVTNkFFDf1V/2stlxKmgDthQemKKv+T2tQQZJTEF8WWTXZKhsXz8LS67N2zsZhfk3jyzBm6QXqv5FpV53tHWCvOFch8Jm6EF6jSZ0JmMhGAjWkhLUbLEgzMug9NUC8mLI4G3NJE7cgoEeEMAiwtU7Yd8nVW//XwX0aJzvZXdDpf7Gmi34CLqWXk2A0rvjcvybM8SFR1pQ6ADEzbRJ+Mqjj1WOzt0f7cdMRLQ/qlUAgFW0WRW2vWGlt/LOZrA4uDgw69bNhacRgboH8Sa/TLruRpTSjlb3MXmRXrHS3QDDIc99RxHrZ7hnMrP/De2viiKsiBszXMCjQCCtWu78gBM8NhOFjq5CydKtrYE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Aucassin-and-Nicolete_1578
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy